spring:
  application:
    name: googleOauth2

  datasource:
    url: jdbc:postgresql://localhost:5432/dummyname
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret: G
server:
  port: 8080